name: Take Snap

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Create Emulator
        run: |
          sdkmanager "system-images;android-30;google_apis;x86_64"
          echo no | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --force

      - name: Start Emulator
        run: |
          export PATH=$PATH:$ANDROID_HOME/emulator
          emulator -avd test -no-window -no-audio -no-boot-anim &
          adb wait-for-device
          adb shell input keyevent 82

      - name: Install Maestro
        run: curl -Ls "https://get.maestro.mobile.dev" | bash

      - name: Run Tests
        run: maestro test maestro/